# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Turntable(object):
    def setupUi(self, Turntable):
        Turntable.setObjectName("Turntable")
        Turntable.resize(816, 648)
        self.verticalLayout = QtWidgets.QVBoxLayout(Turntable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=Turntable)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.cmbUSB = QtWidgets.QComboBox(parent=Turntable)
        self.cmbUSB.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbUSB.setObjectName("cmbUSB")
        self.horizontalLayout.addWidget(self.cmbUSB)
        self.label_2 = QtWidgets.QLabel(parent=Turntable)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.editFilename = QtWidgets.QLineEdit(parent=Turntable)
        self.editFilename.setObjectName("editFilename")
        self.horizontalLayout.addWidget(self.editFilename)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnStart = QtWidgets.QPushButton(parent=Turntable)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblCam = QtWidgets.QLabel(parent=Turntable)
        self.lblCam.setMinimumSize(QtCore.QSize(800, 600))
        self.lblCam.setText("")
        self.lblCam.setObjectName("lblCam")
        self.verticalLayout.addWidget(self.lblCam)

        self.retranslateUi(Turntable)
        self.btnStart.clicked.connect(Turntable.startCapture) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Turntable)

    def retranslateUi(self, Turntable):
        _translate = QtCore.QCoreApplication.translate
        Turntable.setWindowTitle(_translate("Turntable", "Dialog"))
        self.label_3.setText(_translate("Turntable", "Arduino serial port"))
        self.label_2.setText(_translate("Turntable", "Video file name"))
        self.editFilename.setText(_translate("Turntable", "video.avi"))
        self.btnStart.setText(_translate("Turntable", "Start"))
